name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Build .NET 6"]
    types:
      - completed

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-dotnet6

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dotnet-app
        path: /tmp/dotnet-app

    - name: Build and push Docker image
      run: |
        cd /tmp/dotnet-app
        docker build -t sua-conta-dockerhub/minha-aplicacao-dotnet6:${{ github.run_number }} .
        docker push sua-conta-dockerhub/minha-aplicacao-dotnet6:${{ github.run_number }}
