name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK 6.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Restore dependencies
      run: dotnet restore ./MinhaAplicacaoDotNet6/MinhaAplicacaoWeb/MinhaAplicacaoWeb.csproj

    - name: Build
      run: dotnet build ./MinhaAplicacaoDotNet6/MinhaAplicacaoWeb/MinhaAplicacaoWeb.csproj --configuration Release

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./MinhaAplicacaoDotnet6/MinhaAplicacaoDotnet6.sln
        file: ./MinhaAplicacaoDotnet6/MinhaAplicacaoWeb/Dockerfile
        platforms: linux/amd64
        push: true
        tags: vmoney2021/dotnet6-web-app:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
